/*******************************************************************************
  Turnstone Biologics Confidential
  
  2018 Turnstone Biologics
  All Rights Reserved.
  
  This file is subject to the terms and conditions defined in
  file 'license.txt', which is part of this source code package.
   
  Contributors :
        Turnstone Biologics - General Release
 ******************************************************************************/
package com.occulue.test;

import java.util.logging.*;

/**
 * Base class for application Test classes.
 *
 * @author    your_name_here
 */
public class BaseTest
{
	/**
	 * hidden
	 */
	protected BaseTest() {
	}
	
	public static void runTheTest( Handler logHandler ) 
    {
         try {
		    new ACDCConverterTest().setHandler(logHandler).startTest();
			Thread.sleep(timeToWait);
		    new ACDCConverterDCTerminalTest().setHandler(logHandler).startTest();
			Thread.sleep(timeToWait);
		    new ACDCTerminalTest().setHandler(logHandler).startTest();
			Thread.sleep(timeToWait);
		    new ACLineSegmentTest().setHandler(logHandler).startTest();
			Thread.sleep(timeToWait);
		    new AccumulatorTest().setHandler(logHandler).startTest();
			Thread.sleep(timeToWait);
		    new AccumulatorLimitTest().setHandler(logHandler).startTest();
			Thread.sleep(timeToWait);
		    new AccumulatorLimitSetTest().setHandler(logHandler).startTest();
			Thread.sleep(timeToWait);
		    new AccumulatorResetTest().setHandler(logHandler).startTest();
			Thread.sleep(timeToWait);
		    new AccumulatorValueTest().setHandler(logHandler).startTest();
			Thread.sleep(timeToWait);
		    new ActivePowerTest().setHandler(logHandler).startTest();
			Thread.sleep(timeToWait);
		    new ActivePowerLimitTest().setHandler(logHandler).startTest();
			Thread.sleep(timeToWait);
		    new ActivePowerPerCurrentFlowTest().setHandler(logHandler).startTest();
			Thread.sleep(timeToWait);
		    new ActivePowerPerFrequencyTest().setHandler(logHandler).startTest();
			Thread.sleep(timeToWait);
		    new AnalogTest().setHandler(logHandler).startTest();
			Thread.sleep(timeToWait);
		    new AnalogControlTest().setHandler(logHandler).startTest();
			Thread.sleep(timeToWait);
		    new AnalogLimitTest().setHandler(logHandler).startTest();
			Thread.sleep(timeToWait);
		    new AnalogLimitSetTest().setHandler(logHandler).startTest();
			Thread.sleep(timeToWait);
		    new AnalogValueTest().setHandler(logHandler).startTest();
			Thread.sleep(timeToWait);
		    new AngleDegreesTest().setHandler(logHandler).startTest();
			Thread.sleep(timeToWait);
		    new AngleRadiansTest().setHandler(logHandler).startTest();
			Thread.sleep(timeToWait);
		    new ApparentPowerTest().setHandler(logHandler).startTest();
			Thread.sleep(timeToWait);
		    new ApparentPowerLimitTest().setHandler(logHandler).startTest();
			Thread.sleep(timeToWait);
		    new AreaTest().setHandler(logHandler).startTest();
			Thread.sleep(timeToWait);
		    new AsynchronousMachineTest().setHandler(logHandler).startTest();
			Thread.sleep(timeToWait);
		    new AsynchronousMachineDynamicsTest().setHandler(logHandler).startTest();
			Thread.sleep(timeToWait);
		    new AsynchronousMachineEquivalentCircuitTest().setHandler(logHandler).startTest();
			Thread.sleep(timeToWait);
		    new AsynchronousMachineTimeConstantReactanceTest().setHandler(logHandler).startTest();
			Thread.sleep(timeToWait);
		    new AsynchronousMachineUserDefinedTest().setHandler(logHandler).startTest();
			Thread.sleep(timeToWait);
		    new BaseVoltageTest().setHandler(logHandler).startTest();
			Thread.sleep(timeToWait);
		    new BasicIntervalScheduleTest().setHandler(logHandler).startTest();
			Thread.sleep(timeToWait);
		    new BayTest().setHandler(logHandler).startTest();
			Thread.sleep(timeToWait);
		    new BooleanProxyTest().setHandler(logHandler).startTest();
			Thread.sleep(timeToWait);
		    new BoundaryExtensionsTest().setHandler(logHandler).startTest();
			Thread.sleep(timeToWait);
		    new BreakerTest().setHandler(logHandler).startTest();
			Thread.sleep(timeToWait);
		    new BusNameMarkerTest().setHandler(logHandler).startTest();
			Thread.sleep(timeToWait);
		    new BusbarSectionTest().setHandler(logHandler).startTest();
			Thread.sleep(timeToWait);
		    new CapacitanceTest().setHandler(logHandler).startTest();
			Thread.sleep(timeToWait);
		    new CapacitancePerLengthTest().setHandler(logHandler).startTest();
			Thread.sleep(timeToWait);
		    new CommandTest().setHandler(logHandler).startTest();
			Thread.sleep(timeToWait);
		    new ConductanceTest().setHandler(logHandler).startTest();
			Thread.sleep(timeToWait);
		    new ConductingEquipmentTest().setHandler(logHandler).startTest();
			Thread.sleep(timeToWait);
		    new ConductorTest().setHandler(logHandler).startTest();
			Thread.sleep(timeToWait);
		    new ConformLoadTest().setHandler(logHandler).startTest();
			Thread.sleep(timeToWait);
		    new ConformLoadGroupTest().setHandler(logHandler).startTest();
			Thread.sleep(timeToWait);
		    new ConformLoadScheduleTest().setHandler(logHandler).startTest();
			Thread.sleep(timeToWait);
		    new ConnectivityNodeTest().setHandler(logHandler).startTest();
			Thread.sleep(timeToWait);
		    new ConnectivityNodeContainerTest().setHandler(logHandler).startTest();
			Thread.sleep(timeToWait);
		    new ConnectorTest().setHandler(logHandler).startTest();
			Thread.sleep(timeToWait);
		    new ControlTest().setHandler(logHandler).startTest();
			Thread.sleep(timeToWait);
		    new ControlAreaTest().setHandler(logHandler).startTest();
			Thread.sleep(timeToWait);
		    new ControlAreaGeneratingUnitTest().setHandler(logHandler).startTest();
			Thread.sleep(timeToWait);
		    new CoordinateSystemTest().setHandler(logHandler).startTest();
			Thread.sleep(timeToWait);
		    new CsConverterTest().setHandler(logHandler).startTest();
			Thread.sleep(timeToWait);
		    new CurrentFlowTest().setHandler(logHandler).startTest();
			Thread.sleep(timeToWait);
		    new CurrentLimitTest().setHandler(logHandler).startTest();
			Thread.sleep(timeToWait);
		    new CurveTest().setHandler(logHandler).startTest();
			Thread.sleep(timeToWait);
		    new CurveDataTest().setHandler(logHandler).startTest();
			Thread.sleep(timeToWait);
		    new DCBaseTerminalTest().setHandler(logHandler).startTest();
			Thread.sleep(timeToWait);
		    new DCBreakerTest().setHandler(logHandler).startTest();
			Thread.sleep(timeToWait);
		    new DCBusbarTest().setHandler(logHandler).startTest();
			Thread.sleep(timeToWait);
		    new DCChopperTest().setHandler(logHandler).startTest();
			Thread.sleep(timeToWait);
		    new DCConductingEquipmentTest().setHandler(logHandler).startTest();
			Thread.sleep(timeToWait);
		    new DCConverterUnitTest().setHandler(logHandler).startTest();
			Thread.sleep(timeToWait);
		    new DCDisconnectorTest().setHandler(logHandler).startTest();
			Thread.sleep(timeToWait);
		    new DCEquipmentContainerTest().setHandler(logHandler).startTest();
			Thread.sleep(timeToWait);
		    new DCGroundTest().setHandler(logHandler).startTest();
			Thread.sleep(timeToWait);
		    new DCLineTest().setHandler(logHandler).startTest();
			Thread.sleep(timeToWait);
		    new DCLineSegmentTest().setHandler(logHandler).startTest();
			Thread.sleep(timeToWait);
		    new DCNodeTest().setHandler(logHandler).startTest();
			Thread.sleep(timeToWait);
		    new DCSeriesDeviceTest().setHandler(logHandler).startTest();
			Thread.sleep(timeToWait);
		    new DCShuntTest().setHandler(logHandler).startTest();
			Thread.sleep(timeToWait);
		    new DCSwitchTest().setHandler(logHandler).startTest();
			Thread.sleep(timeToWait);
		    new DCTerminalTest().setHandler(logHandler).startTest();
			Thread.sleep(timeToWait);
		    new DCTopologicalIslandTest().setHandler(logHandler).startTest();
			Thread.sleep(timeToWait);
		    new DCTopologicalNodeTest().setHandler(logHandler).startTest();
			Thread.sleep(timeToWait);
		    new DateProxyTest().setHandler(logHandler).startTest();
			Thread.sleep(timeToWait);
		    new DateTimeTest().setHandler(logHandler).startTest();
			Thread.sleep(timeToWait);
		    new DayTypeTest().setHandler(logHandler).startTest();
			Thread.sleep(timeToWait);
		    new DecimalProxyTest().setHandler(logHandler).startTest();
			Thread.sleep(timeToWait);
		    new DiagramTest().setHandler(logHandler).startTest();
			Thread.sleep(timeToWait);
		    new DiagramLayoutVersionTest().setHandler(logHandler).startTest();
			Thread.sleep(timeToWait);
		    new DiagramObjectTest().setHandler(logHandler).startTest();
			Thread.sleep(timeToWait);
		    new DiagramObjectGluePointTest().setHandler(logHandler).startTest();
			Thread.sleep(timeToWait);
		    new DiagramObjectPointTest().setHandler(logHandler).startTest();
			Thread.sleep(timeToWait);
		    new DiagramObjectStyleTest().setHandler(logHandler).startTest();
			Thread.sleep(timeToWait);
		    new DiagramStyleTest().setHandler(logHandler).startTest();
			Thread.sleep(timeToWait);
		    new DiscExcContIEEEDEC1ATest().setHandler(logHandler).startTest();
			Thread.sleep(timeToWait);
		    new DiscExcContIEEEDEC2ATest().setHandler(logHandler).startTest();
			Thread.sleep(timeToWait);
		    new DiscExcContIEEEDEC3ATest().setHandler(logHandler).startTest();
			Thread.sleep(timeToWait);
		    new DisconnectorTest().setHandler(logHandler).startTest();
			Thread.sleep(timeToWait);
		    new DiscontinuousExcitationControlDynamicsTest().setHandler(logHandler).startTest();
			Thread.sleep(timeToWait);
		    new DiscontinuousExcitationControlUserDefinedTest().setHandler(logHandler).startTest();
			Thread.sleep(timeToWait);
		    new DiscreteTest().setHandler(logHandler).startTest();
			Thread.sleep(timeToWait);
		    new DiscreteValueTest().setHandler(logHandler).startTest();
			Thread.sleep(timeToWait);
		    new DomainVersionTest().setHandler(logHandler).startTest();
			Thread.sleep(timeToWait);
		    new DynamicsFunctionBlockTest().setHandler(logHandler).startTest();
			Thread.sleep(timeToWait);
		    new DynamicsVersionTest().setHandler(logHandler).startTest();
			Thread.sleep(timeToWait);
		    new DynamicsmodelTest().setHandler(logHandler).startTest();
			Thread.sleep(timeToWait);
		    new ENTSOEConnectivityNodeTest().setHandler(logHandler).startTest();
			Thread.sleep(timeToWait);
		    new ENTSOEIdentifiedObjectTest().setHandler(logHandler).startTest();
			Thread.sleep(timeToWait);
		    new ENTSOEJunctionTest().setHandler(logHandler).startTest();
			Thread.sleep(timeToWait);
		    new ENTSOEOperationalLimitTypeTest().setHandler(logHandler).startTest();
			Thread.sleep(timeToWait);
		    new ENTSOETopologicalNodeTest().setHandler(logHandler).startTest();
			Thread.sleep(timeToWait);
		    new EarthFaultCompensatorTest().setHandler(logHandler).startTest();
			Thread.sleep(timeToWait);
		    new EnergyAreaTest().setHandler(logHandler).startTest();
			Thread.sleep(timeToWait);
		    new EnergyConsumerTest().setHandler(logHandler).startTest();
			Thread.sleep(timeToWait);
		    new EnergySchedulingTypeTest().setHandler(logHandler).startTest();
			Thread.sleep(timeToWait);
		    new EnergySourceTest().setHandler(logHandler).startTest();
			Thread.sleep(timeToWait);
		    new EquipmentTest().setHandler(logHandler).startTest();
			Thread.sleep(timeToWait);
		    new EquipmentBoundaryVersionTest().setHandler(logHandler).startTest();
			Thread.sleep(timeToWait);
		    new EquipmentContainerTest().setHandler(logHandler).startTest();
			Thread.sleep(timeToWait);
		    new EquipmentVersionTest().setHandler(logHandler).startTest();
			Thread.sleep(timeToWait);
		    new EquivalentBranchTest().setHandler(logHandler).startTest();
			Thread.sleep(timeToWait);
		    new EquivalentEquipmentTest().setHandler(logHandler).startTest();
			Thread.sleep(timeToWait);
		    new EquivalentInjectionTest().setHandler(logHandler).startTest();
			Thread.sleep(timeToWait);
		    new EquivalentNetworkTest().setHandler(logHandler).startTest();
			Thread.sleep(timeToWait);
		    new EquivalentShuntTest().setHandler(logHandler).startTest();
			Thread.sleep(timeToWait);
		    new ExcAC1ATest().setHandler(logHandler).startTest();
			Thread.sleep(timeToWait);
		    new ExcAC2ATest().setHandler(logHandler).startTest();
			Thread.sleep(timeToWait);
		    new ExcAC3ATest().setHandler(logHandler).startTest();
			Thread.sleep(timeToWait);
		    new ExcAC4ATest().setHandler(logHandler).startTest();
			Thread.sleep(timeToWait);
		    new ExcAC5ATest().setHandler(logHandler).startTest();
			Thread.sleep(timeToWait);
		    new ExcAC6ATest().setHandler(logHandler).startTest();
			Thread.sleep(timeToWait);
		    new ExcAC8BTest().setHandler(logHandler).startTest();
			Thread.sleep(timeToWait);
		    new ExcANSTest().setHandler(logHandler).startTest();
			Thread.sleep(timeToWait);
		    new ExcAVR1Test().setHandler(logHandler).startTest();
			Thread.sleep(timeToWait);
		    new ExcAVR2Test().setHandler(logHandler).startTest();
			Thread.sleep(timeToWait);
		    new ExcAVR3Test().setHandler(logHandler).startTest();
			Thread.sleep(timeToWait);
		    new ExcAVR4Test().setHandler(logHandler).startTest();
			Thread.sleep(timeToWait);
		    new ExcAVR5Test().setHandler(logHandler).startTest();
			Thread.sleep(timeToWait);
		    new ExcAVR7Test().setHandler(logHandler).startTest();
			Thread.sleep(timeToWait);
		    new ExcBBCTest().setHandler(logHandler).startTest();
			Thread.sleep(timeToWait);
		    new ExcCZTest().setHandler(logHandler).startTest();
			Thread.sleep(timeToWait);
		    new ExcDC1ATest().setHandler(logHandler).startTest();
			Thread.sleep(timeToWait);
		    new ExcDC2ATest().setHandler(logHandler).startTest();
			Thread.sleep(timeToWait);
		    new ExcDC3ATest().setHandler(logHandler).startTest();
			Thread.sleep(timeToWait);
		    new ExcDC3A1Test().setHandler(logHandler).startTest();
			Thread.sleep(timeToWait);
		    new ExcELIN1Test().setHandler(logHandler).startTest();
			Thread.sleep(timeToWait);
		    new ExcELIN2Test().setHandler(logHandler).startTest();
			Thread.sleep(timeToWait);
		    new ExcHUTest().setHandler(logHandler).startTest();
			Thread.sleep(timeToWait);
		    new ExcIEEEAC1ATest().setHandler(logHandler).startTest();
			Thread.sleep(timeToWait);
		    new ExcIEEEAC2ATest().setHandler(logHandler).startTest();
			Thread.sleep(timeToWait);
		    new ExcIEEEAC3ATest().setHandler(logHandler).startTest();
			Thread.sleep(timeToWait);
		    new ExcIEEEAC4ATest().setHandler(logHandler).startTest();
			Thread.sleep(timeToWait);
		    new ExcIEEEAC5ATest().setHandler(logHandler).startTest();
			Thread.sleep(timeToWait);
		    new ExcIEEEAC6ATest().setHandler(logHandler).startTest();
			Thread.sleep(timeToWait);
		    new ExcIEEEAC7BTest().setHandler(logHandler).startTest();
			Thread.sleep(timeToWait);
		    new ExcIEEEAC8BTest().setHandler(logHandler).startTest();
			Thread.sleep(timeToWait);
		    new ExcIEEEDC1ATest().setHandler(logHandler).startTest();
			Thread.sleep(timeToWait);
		    new ExcIEEEDC2ATest().setHandler(logHandler).startTest();
			Thread.sleep(timeToWait);
		    new ExcIEEEDC3ATest().setHandler(logHandler).startTest();
			Thread.sleep(timeToWait);
		    new ExcIEEEDC4BTest().setHandler(logHandler).startTest();
			Thread.sleep(timeToWait);
		    new ExcIEEEST1ATest().setHandler(logHandler).startTest();
			Thread.sleep(timeToWait);
		    new ExcIEEEST2ATest().setHandler(logHandler).startTest();
			Thread.sleep(timeToWait);
		    new ExcIEEEST3ATest().setHandler(logHandler).startTest();
			Thread.sleep(timeToWait);
		    new ExcIEEEST4BTest().setHandler(logHandler).startTest();
			Thread.sleep(timeToWait);
		    new ExcIEEEST5BTest().setHandler(logHandler).startTest();
			Thread.sleep(timeToWait);
		    new ExcIEEEST6BTest().setHandler(logHandler).startTest();
			Thread.sleep(timeToWait);
		    new ExcIEEEST7BTest().setHandler(logHandler).startTest();
			Thread.sleep(timeToWait);
		    new ExcOEX3TTest().setHandler(logHandler).startTest();
			Thread.sleep(timeToWait);
		    new ExcPICTest().setHandler(logHandler).startTest();
			Thread.sleep(timeToWait);
		    new ExcREXSTest().setHandler(logHandler).startTest();
			Thread.sleep(timeToWait);
		    new ExcSCRXTest().setHandler(logHandler).startTest();
			Thread.sleep(timeToWait);
		    new ExcSEXSTest().setHandler(logHandler).startTest();
			Thread.sleep(timeToWait);
		    new ExcSKTest().setHandler(logHandler).startTest();
			Thread.sleep(timeToWait);
		    new ExcST1ATest().setHandler(logHandler).startTest();
			Thread.sleep(timeToWait);
		    new ExcST2ATest().setHandler(logHandler).startTest();
			Thread.sleep(timeToWait);
		    new ExcST3ATest().setHandler(logHandler).startTest();
			Thread.sleep(timeToWait);
		    new ExcST4BTest().setHandler(logHandler).startTest();
			Thread.sleep(timeToWait);
		    new ExcST6BTest().setHandler(logHandler).startTest();
			Thread.sleep(timeToWait);
		    new ExcST7BTest().setHandler(logHandler).startTest();
			Thread.sleep(timeToWait);
		    new ExcitationSystemDynamicsTest().setHandler(logHandler).startTest();
			Thread.sleep(timeToWait);
		    new ExcitationSystemUserDefinedTest().setHandler(logHandler).startTest();
			Thread.sleep(timeToWait);
		    new ExtensionVersionTest().setHandler(logHandler).startTest();
			Thread.sleep(timeToWait);
		    new ExternalNetworkInjectionTest().setHandler(logHandler).startTest();
			Thread.sleep(timeToWait);
		    new FloatProxyTest().setHandler(logHandler).startTest();
			Thread.sleep(timeToWait);
		    new FossilFuelTest().setHandler(logHandler).startTest();
			Thread.sleep(timeToWait);
		    new FrequencyTest().setHandler(logHandler).startTest();
			Thread.sleep(timeToWait);
		    new GenICompensationForGenJTest().setHandler(logHandler).startTest();
			Thread.sleep(timeToWait);
		    new GeneratingUnitTest().setHandler(logHandler).startTest();
			Thread.sleep(timeToWait);
		    new GeographicalLocationVersionTest().setHandler(logHandler).startTest();
			Thread.sleep(timeToWait);
		    new GeographicalRegionTest().setHandler(logHandler).startTest();
			Thread.sleep(timeToWait);
		    new GovCT1Test().setHandler(logHandler).startTest();
			Thread.sleep(timeToWait);
		    new GovCT2Test().setHandler(logHandler).startTest();
			Thread.sleep(timeToWait);
		    new GovGASTTest().setHandler(logHandler).startTest();
			Thread.sleep(timeToWait);
		    new GovGAST1Test().setHandler(logHandler).startTest();
			Thread.sleep(timeToWait);
		    new GovGAST2Test().setHandler(logHandler).startTest();
			Thread.sleep(timeToWait);
		    new GovGAST3Test().setHandler(logHandler).startTest();
			Thread.sleep(timeToWait);
		    new GovGAST4Test().setHandler(logHandler).startTest();
			Thread.sleep(timeToWait);
		    new GovGASTWDTest().setHandler(logHandler).startTest();
			Thread.sleep(timeToWait);
		    new GovHydro1Test().setHandler(logHandler).startTest();
			Thread.sleep(timeToWait);
		    new GovHydro2Test().setHandler(logHandler).startTest();
			Thread.sleep(timeToWait);
		    new GovHydro3Test().setHandler(logHandler).startTest();
			Thread.sleep(timeToWait);
		    new GovHydro4Test().setHandler(logHandler).startTest();
			Thread.sleep(timeToWait);
		    new GovHydroDDTest().setHandler(logHandler).startTest();
			Thread.sleep(timeToWait);
		    new GovHydroFrancisTest().setHandler(logHandler).startTest();
			Thread.sleep(timeToWait);
		    new GovHydroIEEE0Test().setHandler(logHandler).startTest();
			Thread.sleep(timeToWait);
		    new GovHydroIEEE2Test().setHandler(logHandler).startTest();
			Thread.sleep(timeToWait);
		    new GovHydroPIDTest().setHandler(logHandler).startTest();
			Thread.sleep(timeToWait);
		    new GovHydroPID2Test().setHandler(logHandler).startTest();
			Thread.sleep(timeToWait);
		    new GovHydroPeltonTest().setHandler(logHandler).startTest();
			Thread.sleep(timeToWait);
		    new GovHydroRTest().setHandler(logHandler).startTest();
			Thread.sleep(timeToWait);
		    new GovHydroWEHTest().setHandler(logHandler).startTest();
			Thread.sleep(timeToWait);
		    new GovHydroWPIDTest().setHandler(logHandler).startTest();
			Thread.sleep(timeToWait);
		    new GovSteam0Test().setHandler(logHandler).startTest();
			Thread.sleep(timeToWait);
		    new GovSteam1Test().setHandler(logHandler).startTest();
			Thread.sleep(timeToWait);
		    new GovSteam2Test().setHandler(logHandler).startTest();
			Thread.sleep(timeToWait);
		    new GovSteamCCTest().setHandler(logHandler).startTest();
			Thread.sleep(timeToWait);
		    new GovSteamEUTest().setHandler(logHandler).startTest();
			Thread.sleep(timeToWait);
		    new GovSteamFV2Test().setHandler(logHandler).startTest();
			Thread.sleep(timeToWait);
		    new GovSteamFV3Test().setHandler(logHandler).startTest();
			Thread.sleep(timeToWait);
		    new GovSteamFV4Test().setHandler(logHandler).startTest();
			Thread.sleep(timeToWait);
		    new GovSteamIEEE1Test().setHandler(logHandler).startTest();
			Thread.sleep(timeToWait);
		    new GovSteamSGOTest().setHandler(logHandler).startTest();
			Thread.sleep(timeToWait);
		    new GrossToNetActivePowerCurveTest().setHandler(logHandler).startTest();
			Thread.sleep(timeToWait);
		    new GroundTest().setHandler(logHandler).startTest();
			Thread.sleep(timeToWait);
		    new GroundDisconnectorTest().setHandler(logHandler).startTest();
			Thread.sleep(timeToWait);
		    new GroundingImpedanceTest().setHandler(logHandler).startTest();
			Thread.sleep(timeToWait);
		    new HydroGeneratingUnitTest().setHandler(logHandler).startTest();
			Thread.sleep(timeToWait);
		    new HydroPowerPlantTest().setHandler(logHandler).startTest();
			Thread.sleep(timeToWait);
		    new HydroPumpTest().setHandler(logHandler).startTest();
			Thread.sleep(timeToWait);
		    new IdentifiedObjectTest().setHandler(logHandler).startTest();
			Thread.sleep(timeToWait);
		    new InductanceTest().setHandler(logHandler).startTest();
			Thread.sleep(timeToWait);
		    new InductancePerLengthTest().setHandler(logHandler).startTest();
			Thread.sleep(timeToWait);
		    new IntegerProxyTest().setHandler(logHandler).startTest();
			Thread.sleep(timeToWait);
		    new JunctionTest().setHandler(logHandler).startTest();
			Thread.sleep(timeToWait);
		    new LengthTest().setHandler(logHandler).startTest();
			Thread.sleep(timeToWait);
		    new LimitTest().setHandler(logHandler).startTest();
			Thread.sleep(timeToWait);
		    new LimitSetTest().setHandler(logHandler).startTest();
			Thread.sleep(timeToWait);
		    new LineTest().setHandler(logHandler).startTest();
			Thread.sleep(timeToWait);
		    new LinearShuntCompensatorTest().setHandler(logHandler).startTest();
			Thread.sleep(timeToWait);
		    new LoadAggregateTest().setHandler(logHandler).startTest();
			Thread.sleep(timeToWait);
		    new LoadAreaTest().setHandler(logHandler).startTest();
			Thread.sleep(timeToWait);
		    new LoadBreakSwitchTest().setHandler(logHandler).startTest();
			Thread.sleep(timeToWait);
		    new LoadCompositeTest().setHandler(logHandler).startTest();
			Thread.sleep(timeToWait);
		    new LoadDynamicsTest().setHandler(logHandler).startTest();
			Thread.sleep(timeToWait);
		    new LoadGenericNonLinearTest().setHandler(logHandler).startTest();
			Thread.sleep(timeToWait);
		    new LoadGroupTest().setHandler(logHandler).startTest();
			Thread.sleep(timeToWait);
		    new LoadMotorTest().setHandler(logHandler).startTest();
			Thread.sleep(timeToWait);
		    new LoadResponseCharacteristicTest().setHandler(logHandler).startTest();
			Thread.sleep(timeToWait);
		    new LoadStaticTest().setHandler(logHandler).startTest();
			Thread.sleep(timeToWait);
		    new LoadUserDefinedTest().setHandler(logHandler).startTest();
			Thread.sleep(timeToWait);
		    new LocationTest().setHandler(logHandler).startTest();
			Thread.sleep(timeToWait);
		    new MeasurementTest().setHandler(logHandler).startTest();
			Thread.sleep(timeToWait);
		    new MeasurementValueTest().setHandler(logHandler).startTest();
			Thread.sleep(timeToWait);
		    new MeasurementValueQualityTest().setHandler(logHandler).startTest();
			Thread.sleep(timeToWait);
		    new MeasurementValueSourceTest().setHandler(logHandler).startTest();
			Thread.sleep(timeToWait);
		    new MechLoad1Test().setHandler(logHandler).startTest();
			Thread.sleep(timeToWait);
		    new MechanicalLoadDynamicsTest().setHandler(logHandler).startTest();
			Thread.sleep(timeToWait);
		    new MechanicalLoadUserDefinedTest().setHandler(logHandler).startTest();
			Thread.sleep(timeToWait);
		    new MoneyTest().setHandler(logHandler).startTest();
			Thread.sleep(timeToWait);
		    new MonthDayTest().setHandler(logHandler).startTest();
			Thread.sleep(timeToWait);
		    new MonthDayIntervalTest().setHandler(logHandler).startTest();
			Thread.sleep(timeToWait);
		    new MutualCouplingTest().setHandler(logHandler).startTest();
			Thread.sleep(timeToWait);
		    new NonConformLoadTest().setHandler(logHandler).startTest();
			Thread.sleep(timeToWait);
		    new NonConformLoadGroupTest().setHandler(logHandler).startTest();
			Thread.sleep(timeToWait);
		    new NonConformLoadScheduleTest().setHandler(logHandler).startTest();
			Thread.sleep(timeToWait);
		    new NonlinearShuntCompensatorTest().setHandler(logHandler).startTest();
			Thread.sleep(timeToWait);
		    new NonlinearShuntCompensatorPointTest().setHandler(logHandler).startTest();
			Thread.sleep(timeToWait);
		    new NuclearGeneratingUnitTest().setHandler(logHandler).startTest();
			Thread.sleep(timeToWait);
		    new OperationalLimitTest().setHandler(logHandler).startTest();
			Thread.sleep(timeToWait);
		    new OperationalLimitSetTest().setHandler(logHandler).startTest();
			Thread.sleep(timeToWait);
		    new OperationalLimitTypeTest().setHandler(logHandler).startTest();
			Thread.sleep(timeToWait);
		    new OverexcLim2Test().setHandler(logHandler).startTest();
			Thread.sleep(timeToWait);
		    new OverexcLimIEEETest().setHandler(logHandler).startTest();
			Thread.sleep(timeToWait);
		    new OverexcLimX1Test().setHandler(logHandler).startTest();
			Thread.sleep(timeToWait);
		    new OverexcLimX2Test().setHandler(logHandler).startTest();
			Thread.sleep(timeToWait);
		    new OverexcitationLimiterDynamicsTest().setHandler(logHandler).startTest();
			Thread.sleep(timeToWait);
		    new OverexcitationLimiterUserDefinedTest().setHandler(logHandler).startTest();
			Thread.sleep(timeToWait);
		    new PFVArControllerType1DynamicsTest().setHandler(logHandler).startTest();
			Thread.sleep(timeToWait);
		    new PFVArControllerType1UserDefinedTest().setHandler(logHandler).startTest();
			Thread.sleep(timeToWait);
		    new PFVArControllerType2DynamicsTest().setHandler(logHandler).startTest();
			Thread.sleep(timeToWait);
		    new PFVArControllerType2UserDefinedTest().setHandler(logHandler).startTest();
			Thread.sleep(timeToWait);
		    new PFVArType1IEEEPFControllerTest().setHandler(logHandler).startTest();
			Thread.sleep(timeToWait);
		    new PFVArType1IEEEVArControllerTest().setHandler(logHandler).startTest();
			Thread.sleep(timeToWait);
		    new PFVArType2Common1Test().setHandler(logHandler).startTest();
			Thread.sleep(timeToWait);
		    new PFVArType2IEEEPFControllerTest().setHandler(logHandler).startTest();
			Thread.sleep(timeToWait);
		    new PFVArType2IEEEVArControllerTest().setHandler(logHandler).startTest();
			Thread.sleep(timeToWait);
		    new PUTest().setHandler(logHandler).startTest();
			Thread.sleep(timeToWait);
		    new PerCentTest().setHandler(logHandler).startTest();
			Thread.sleep(timeToWait);
		    new PerLengthDCLineParameterTest().setHandler(logHandler).startTest();
			Thread.sleep(timeToWait);
		    new PetersenCoilTest().setHandler(logHandler).startTest();
			Thread.sleep(timeToWait);
		    new PhaseTapChangerTest().setHandler(logHandler).startTest();
			Thread.sleep(timeToWait);
		    new PhaseTapChangerAsymmetricalTest().setHandler(logHandler).startTest();
			Thread.sleep(timeToWait);
		    new PhaseTapChangerLinearTest().setHandler(logHandler).startTest();
			Thread.sleep(timeToWait);
		    new PhaseTapChangerNonLinearTest().setHandler(logHandler).startTest();
			Thread.sleep(timeToWait);
		    new PhaseTapChangerSymmetricalTest().setHandler(logHandler).startTest();
			Thread.sleep(timeToWait);
		    new PhaseTapChangerTableTest().setHandler(logHandler).startTest();
			Thread.sleep(timeToWait);
		    new PhaseTapChangerTablePointTest().setHandler(logHandler).startTest();
			Thread.sleep(timeToWait);
		    new PhaseTapChangerTabularTest().setHandler(logHandler).startTest();
			Thread.sleep(timeToWait);
		    new PositionPointTest().setHandler(logHandler).startTest();
			Thread.sleep(timeToWait);
		    new PowerSystemResourceTest().setHandler(logHandler).startTest();
			Thread.sleep(timeToWait);
		    new PowerSystemStabilizerDynamicsTest().setHandler(logHandler).startTest();
			Thread.sleep(timeToWait);
		    new PowerSystemStabilizerUserDefinedTest().setHandler(logHandler).startTest();
			Thread.sleep(timeToWait);
		    new PowerTransformerTest().setHandler(logHandler).startTest();
			Thread.sleep(timeToWait);
		    new PowerTransformerEndTest().setHandler(logHandler).startTest();
			Thread.sleep(timeToWait);
		    new ProprietaryParameterDynamicsTest().setHandler(logHandler).startTest();
			Thread.sleep(timeToWait);
		    new ProtectedSwitchTest().setHandler(logHandler).startTest();
			Thread.sleep(timeToWait);
		    new Pss1Test().setHandler(logHandler).startTest();
			Thread.sleep(timeToWait);
		    new Pss1ATest().setHandler(logHandler).startTest();
			Thread.sleep(timeToWait);
		    new Pss2BTest().setHandler(logHandler).startTest();
			Thread.sleep(timeToWait);
		    new Pss2STTest().setHandler(logHandler).startTest();
			Thread.sleep(timeToWait);
		    new Pss5Test().setHandler(logHandler).startTest();
			Thread.sleep(timeToWait);
		    new PssELIN2Test().setHandler(logHandler).startTest();
			Thread.sleep(timeToWait);
		    new PssIEEE1ATest().setHandler(logHandler).startTest();
			Thread.sleep(timeToWait);
		    new PssIEEE2BTest().setHandler(logHandler).startTest();
			Thread.sleep(timeToWait);
		    new PssIEEE3BTest().setHandler(logHandler).startTest();
			Thread.sleep(timeToWait);
		    new PssIEEE4BTest().setHandler(logHandler).startTest();
			Thread.sleep(timeToWait);
		    new PssPTIST1Test().setHandler(logHandler).startTest();
			Thread.sleep(timeToWait);
		    new PssPTIST3Test().setHandler(logHandler).startTest();
			Thread.sleep(timeToWait);
		    new PssSB4Test().setHandler(logHandler).startTest();
			Thread.sleep(timeToWait);
		    new PssSHTest().setHandler(logHandler).startTest();
			Thread.sleep(timeToWait);
		    new PssSKTest().setHandler(logHandler).startTest();
			Thread.sleep(timeToWait);
		    new PssWECCTest().setHandler(logHandler).startTest();
			Thread.sleep(timeToWait);
		    new Quality61850Test().setHandler(logHandler).startTest();
			Thread.sleep(timeToWait);
		    new RaiseLowerCommandTest().setHandler(logHandler).startTest();
			Thread.sleep(timeToWait);
		    new RatioTapChangerTest().setHandler(logHandler).startTest();
			Thread.sleep(timeToWait);
		    new RatioTapChangerTableTest().setHandler(logHandler).startTest();
			Thread.sleep(timeToWait);
		    new RatioTapChangerTablePointTest().setHandler(logHandler).startTest();
			Thread.sleep(timeToWait);
		    new ReactanceTest().setHandler(logHandler).startTest();
			Thread.sleep(timeToWait);
		    new ReactiveCapabilityCurveTest().setHandler(logHandler).startTest();
			Thread.sleep(timeToWait);
		    new ReactivePowerTest().setHandler(logHandler).startTest();
			Thread.sleep(timeToWait);
		    new RegularIntervalScheduleTest().setHandler(logHandler).startTest();
			Thread.sleep(timeToWait);
		    new RegularTimePointTest().setHandler(logHandler).startTest();
			Thread.sleep(timeToWait);
		    new RegulatingCondEqTest().setHandler(logHandler).startTest();
			Thread.sleep(timeToWait);
		    new RegulatingControlTest().setHandler(logHandler).startTest();
			Thread.sleep(timeToWait);
		    new RegulationScheduleTest().setHandler(logHandler).startTest();
			Thread.sleep(timeToWait);
		    new RemoteInputSignalTest().setHandler(logHandler).startTest();
			Thread.sleep(timeToWait);
		    new ReportingGroupTest().setHandler(logHandler).startTest();
			Thread.sleep(timeToWait);
		    new ResistanceTest().setHandler(logHandler).startTest();
			Thread.sleep(timeToWait);
		    new ResistancePerLengthTest().setHandler(logHandler).startTest();
			Thread.sleep(timeToWait);
		    new RotatingMachineTest().setHandler(logHandler).startTest();
			Thread.sleep(timeToWait);
		    new RotatingMachineDynamicsTest().setHandler(logHandler).startTest();
			Thread.sleep(timeToWait);
		    new RotationSpeedTest().setHandler(logHandler).startTest();
			Thread.sleep(timeToWait);
		    new SeasonTest().setHandler(logHandler).startTest();
			Thread.sleep(timeToWait);
		    new SeasonDayTypeScheduleTest().setHandler(logHandler).startTest();
			Thread.sleep(timeToWait);
		    new SecondsTest().setHandler(logHandler).startTest();
			Thread.sleep(timeToWait);
		    new SeriesCompensatorTest().setHandler(logHandler).startTest();
			Thread.sleep(timeToWait);
		    new SetPointTest().setHandler(logHandler).startTest();
			Thread.sleep(timeToWait);
		    new ShuntCompensatorTest().setHandler(logHandler).startTest();
			Thread.sleep(timeToWait);
		    new Simple_FloatTest().setHandler(logHandler).startTest();
			Thread.sleep(timeToWait);
		    new SolarGeneratingUnitTest().setHandler(logHandler).startTest();
			Thread.sleep(timeToWait);
		    new StateVariablesVersionTest().setHandler(logHandler).startTest();
			Thread.sleep(timeToWait);
		    new StaticVarCompensatorTest().setHandler(logHandler).startTest();
			Thread.sleep(timeToWait);
		    new StaticpowersystemmodelTest().setHandler(logHandler).startTest();
			Thread.sleep(timeToWait);
		    new StationSupplyTest().setHandler(logHandler).startTest();
			Thread.sleep(timeToWait);
		    new SteadyStateHypothesisVersionTest().setHandler(logHandler).startTest();
			Thread.sleep(timeToWait);
		    new StringMeasurementTest().setHandler(logHandler).startTest();
			Thread.sleep(timeToWait);
		    new StringMeasurementValueTest().setHandler(logHandler).startTest();
			Thread.sleep(timeToWait);
		    new StringProxyTest().setHandler(logHandler).startTest();
			Thread.sleep(timeToWait);
		    new SubGeographicalRegionTest().setHandler(logHandler).startTest();
			Thread.sleep(timeToWait);
		    new SubLoadAreaTest().setHandler(logHandler).startTest();
			Thread.sleep(timeToWait);
		    new SubstationTest().setHandler(logHandler).startTest();
			Thread.sleep(timeToWait);
		    new SusceptanceTest().setHandler(logHandler).startTest();
			Thread.sleep(timeToWait);
		    new SvInjectionTest().setHandler(logHandler).startTest();
			Thread.sleep(timeToWait);
		    new SvPowerFlowTest().setHandler(logHandler).startTest();
			Thread.sleep(timeToWait);
		    new SvShuntCompensatorSectionsTest().setHandler(logHandler).startTest();
			Thread.sleep(timeToWait);
		    new SvStatusTest().setHandler(logHandler).startTest();
			Thread.sleep(timeToWait);
		    new SvTapStepTest().setHandler(logHandler).startTest();
			Thread.sleep(timeToWait);
		    new SvVoltageTest().setHandler(logHandler).startTest();
			Thread.sleep(timeToWait);
		    new SwitchItTest().setHandler(logHandler).startTest();
			Thread.sleep(timeToWait);
		    new SwitchProxyTest().setHandler(logHandler).startTest();
			Thread.sleep(timeToWait);
		    new SwitchScheduleTest().setHandler(logHandler).startTest();
			Thread.sleep(timeToWait);
		    new SynchronousMachineTest().setHandler(logHandler).startTest();
			Thread.sleep(timeToWait);
		    new SynchronousMachineDetailedTest().setHandler(logHandler).startTest();
			Thread.sleep(timeToWait);
		    new SynchronousMachineDynamicsTest().setHandler(logHandler).startTest();
			Thread.sleep(timeToWait);
		    new SynchronousMachineEquivalentCircuitTest().setHandler(logHandler).startTest();
			Thread.sleep(timeToWait);
		    new SynchronousMachineSimplifiedTest().setHandler(logHandler).startTest();
			Thread.sleep(timeToWait);
		    new SynchronousMachineTimeConstantReactanceTest().setHandler(logHandler).startTest();
			Thread.sleep(timeToWait);
		    new SynchronousMachineUserDefinedTest().setHandler(logHandler).startTest();
			Thread.sleep(timeToWait);
		    new TapChangerTest().setHandler(logHandler).startTest();
			Thread.sleep(timeToWait);
		    new TapChangerControlTest().setHandler(logHandler).startTest();
			Thread.sleep(timeToWait);
		    new TapChangerTablePointTest().setHandler(logHandler).startTest();
			Thread.sleep(timeToWait);
		    new TapScheduleTest().setHandler(logHandler).startTest();
			Thread.sleep(timeToWait);
		    new TemperatureTest().setHandler(logHandler).startTest();
			Thread.sleep(timeToWait);
		    new TerminalTest().setHandler(logHandler).startTest();
			Thread.sleep(timeToWait);
		    new TextDiagramObjectTest().setHandler(logHandler).startTest();
			Thread.sleep(timeToWait);
		    new ThermalGeneratingUnitTest().setHandler(logHandler).startTest();
			Thread.sleep(timeToWait);
		    new TieFlowTest().setHandler(logHandler).startTest();
			Thread.sleep(timeToWait);
		    new TopologicalIslandTest().setHandler(logHandler).startTest();
			Thread.sleep(timeToWait);
		    new TopologicalNodeTest().setHandler(logHandler).startTest();
			Thread.sleep(timeToWait);
		    new TopologyBoundaryVersionTest().setHandler(logHandler).startTest();
			Thread.sleep(timeToWait);
		    new TopologyVersionTest().setHandler(logHandler).startTest();
			Thread.sleep(timeToWait);
		    new TransformerEndTest().setHandler(logHandler).startTest();
			Thread.sleep(timeToWait);
		    new TurbLCFB1Test().setHandler(logHandler).startTest();
			Thread.sleep(timeToWait);
		    new TurbineGovernorDynamicsTest().setHandler(logHandler).startTest();
			Thread.sleep(timeToWait);
		    new TurbineGovernorUserDefinedTest().setHandler(logHandler).startTest();
			Thread.sleep(timeToWait);
		    new TurbineLoadControllerDynamicsTest().setHandler(logHandler).startTest();
			Thread.sleep(timeToWait);
		    new TurbineLoadControllerUserDefinedTest().setHandler(logHandler).startTest();
			Thread.sleep(timeToWait);
		    new UnderexcLim2SimplifiedTest().setHandler(logHandler).startTest();
			Thread.sleep(timeToWait);
		    new UnderexcLimIEEE1Test().setHandler(logHandler).startTest();
			Thread.sleep(timeToWait);
		    new UnderexcLimIEEE2Test().setHandler(logHandler).startTest();
			Thread.sleep(timeToWait);
		    new UnderexcLimX1Test().setHandler(logHandler).startTest();
			Thread.sleep(timeToWait);
		    new UnderexcLimX2Test().setHandler(logHandler).startTest();
			Thread.sleep(timeToWait);
		    new UnderexcitationLimiterDynamicsTest().setHandler(logHandler).startTest();
			Thread.sleep(timeToWait);
		    new UnderexcitationLimiterUserDefinedTest().setHandler(logHandler).startTest();
			Thread.sleep(timeToWait);
		    new UnresolvednameTest().setHandler(logHandler).startTest();
			Thread.sleep(timeToWait);
		    new VAdjIEEETest().setHandler(logHandler).startTest();
			Thread.sleep(timeToWait);
		    new VCompIEEEType1Test().setHandler(logHandler).startTest();
			Thread.sleep(timeToWait);
		    new VCompIEEEType2Test().setHandler(logHandler).startTest();
			Thread.sleep(timeToWait);
		    new ValueAliasSetTest().setHandler(logHandler).startTest();
			Thread.sleep(timeToWait);
		    new ValueToAliasTest().setHandler(logHandler).startTest();
			Thread.sleep(timeToWait);
		    new VisibilityLayerTest().setHandler(logHandler).startTest();
			Thread.sleep(timeToWait);
		    new VoltageTest().setHandler(logHandler).startTest();
			Thread.sleep(timeToWait);
		    new VoltageAdjusterDynamicsTest().setHandler(logHandler).startTest();
			Thread.sleep(timeToWait);
		    new VoltageAdjusterUserDefinedTest().setHandler(logHandler).startTest();
			Thread.sleep(timeToWait);
		    new VoltageCompensatorDynamicsTest().setHandler(logHandler).startTest();
			Thread.sleep(timeToWait);
		    new VoltageCompensatorUserDefinedTest().setHandler(logHandler).startTest();
			Thread.sleep(timeToWait);
		    new VoltageLevelTest().setHandler(logHandler).startTest();
			Thread.sleep(timeToWait);
		    new VoltageLimitTest().setHandler(logHandler).startTest();
			Thread.sleep(timeToWait);
		    new VoltagePerReactivePowerTest().setHandler(logHandler).startTest();
			Thread.sleep(timeToWait);
		    new VolumeFlowRateTest().setHandler(logHandler).startTest();
			Thread.sleep(timeToWait);
		    new VsCapabilityCurveTest().setHandler(logHandler).startTest();
			Thread.sleep(timeToWait);
		    new VsConverterTest().setHandler(logHandler).startTest();
			Thread.sleep(timeToWait);
		    new WindAeroConstIECTest().setHandler(logHandler).startTest();
			Thread.sleep(timeToWait);
		    new WindAeroLinearIECTest().setHandler(logHandler).startTest();
			Thread.sleep(timeToWait);
		    new WindContCurrLimIECTest().setHandler(logHandler).startTest();
			Thread.sleep(timeToWait);
		    new WindContPType3IECTest().setHandler(logHandler).startTest();
			Thread.sleep(timeToWait);
		    new WindContPType4aIECTest().setHandler(logHandler).startTest();
			Thread.sleep(timeToWait);
		    new WindContPType4bIECTest().setHandler(logHandler).startTest();
			Thread.sleep(timeToWait);
		    new WindContPitchAngleIECTest().setHandler(logHandler).startTest();
			Thread.sleep(timeToWait);
		    new WindContQIECTest().setHandler(logHandler).startTest();
			Thread.sleep(timeToWait);
		    new WindContRotorRIECTest().setHandler(logHandler).startTest();
			Thread.sleep(timeToWait);
		    new WindDynamicsLookupTableTest().setHandler(logHandler).startTest();
			Thread.sleep(timeToWait);
		    new WindGenTurbineType1IECTest().setHandler(logHandler).startTest();
			Thread.sleep(timeToWait);
		    new WindGenTurbineType2IECTest().setHandler(logHandler).startTest();
			Thread.sleep(timeToWait);
		    new WindGenTurbineType3IECTest().setHandler(logHandler).startTest();
			Thread.sleep(timeToWait);
		    new WindGenTurbineType3aIECTest().setHandler(logHandler).startTest();
			Thread.sleep(timeToWait);
		    new WindGenTurbineType3bIECTest().setHandler(logHandler).startTest();
			Thread.sleep(timeToWait);
		    new WindGenType4IECTest().setHandler(logHandler).startTest();
			Thread.sleep(timeToWait);
		    new WindGeneratingUnitTest().setHandler(logHandler).startTest();
			Thread.sleep(timeToWait);
		    new WindMechIECTest().setHandler(logHandler).startTest();
			Thread.sleep(timeToWait);
		    new WindPitchContEmulIECTest().setHandler(logHandler).startTest();
			Thread.sleep(timeToWait);
		    new WindPlantDynamicsTest().setHandler(logHandler).startTest();
			Thread.sleep(timeToWait);
		    new WindPlantFreqPcontrolIECTest().setHandler(logHandler).startTest();
			Thread.sleep(timeToWait);
		    new WindPlantIECTest().setHandler(logHandler).startTest();
			Thread.sleep(timeToWait);
		    new WindPlantReactiveControlIECTest().setHandler(logHandler).startTest();
			Thread.sleep(timeToWait);
		    new WindPlantUserDefinedTest().setHandler(logHandler).startTest();
			Thread.sleep(timeToWait);
		    new WindProtectionIECTest().setHandler(logHandler).startTest();
			Thread.sleep(timeToWait);
		    new WindTurbineType1or2DynamicsTest().setHandler(logHandler).startTest();
			Thread.sleep(timeToWait);
		    new WindTurbineType1or2IECTest().setHandler(logHandler).startTest();
			Thread.sleep(timeToWait);
		    new WindTurbineType3or4DynamicsTest().setHandler(logHandler).startTest();
			Thread.sleep(timeToWait);
		    new WindTurbineType3or4IECTest().setHandler(logHandler).startTest();
			Thread.sleep(timeToWait);
		    new WindTurbineType4aIECTest().setHandler(logHandler).startTest();
			Thread.sleep(timeToWait);
		    new WindTurbineType4bIECTest().setHandler(logHandler).startTest();
			Thread.sleep(timeToWait);
		    new WindType1or2UserDefinedTest().setHandler(logHandler).startTest();
			Thread.sleep(timeToWait);
		    new WindType3or4UserDefinedTest().setHandler(logHandler).startTest();
			Thread.sleep(timeToWait);
        } catch( Throwable exc ) {
        	exc.printStackTrace();
        }
    }
	//-----------------------------------------------------
	// attributes
	//-----------------------------------------------------
	private static final Integer timeToWait = 5000; //milliseconds
}
